master_only: &master_only
  filters:
    branches:
      only: master
develop_only: &develop_only
  filters:
    branches:
      only: develop
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
jobs:
  build:
    docker:
      - image: circleci/openjdk:15-jdk-buster
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-
      - setup_remote_docker:
          version: 19.03.13
      - run: ./gradlew bootBuildImage --imageName=316189508164.dkr.ecr.ap-northeast-1.amazonaws.com/building-service:$CIRCLE_SHA1
      - save_cache:
          paths:
            - ~/.gradle
          key: dependencies-{{ checksum "build.gradle" }}
      - run: docker image tag 316189508164.dkr.ecr.ap-northeast-1.amazonaws.com/building-service:$CIRCLE_SHA1 316189508164.dkr.ecr.ap-northeast-1.amazonaws.com/building-service:latest
      - aws-ecr/ecr-login
      - aws-ecr/push-image:
          repo: building-service
          tag: 'latest,$CIRCLE_SHA1'
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "98:9b:ef:8b:7b:07:6f:df:09:3b:a7:ea:6d:c5:4f:e1"
      - run:
          name: Deploy to EC2 via SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /home/ubuntu/building/building-service/ && docker-compose down && docker-compose pull && docker-compose up -d"
  deploy-staging:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "98:9b:ef:8b:7b:07:6f:df:09:3b:a7:ea:6d:c5:4f:e1"
      - run:
          name: Deploy to EC2 via SSH
          command: |
            ssh $SSH_USER@$SSH_STAGING_HOST "cd /home/ubuntu/building/building-service/ && docker-compose down && docker-compose pull && docker-compose up -d"
workflows:
  version: 2.1
  main:
    jobs:
      - build
      - deploy:
          requires:
            - build
          <<: *master_only
      - deploy-staging:
          requires:
            - build
          <<: *develop_only
